development:
  adapter: postgresql
  encoding: utf8
  database: blog_development
  pool: 5
  username: blog
  password: blog

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: blog_test
  pool: 5
  username: blog
  password: blog

production:
  adapter: postgresql
  encoding: utf8
  database: blog_production
  pool: 5
  username: blog
  password: blog
